backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "board"
    label: "Board Members"
    folder: "src/board"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Qualifications", name: "qualifications", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/member.html"}

  - name: "team"
    label: "Team Members"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Qualifications", name: "qualifications", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Large Image", name: "imageLarge", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - {label: "Block Quote", name: "blockQuote", widget: "text", required: false}
      - {label: "Detailed Bio", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/member.html"}

  - name: "faqs"
    label: "FAQs"
    folder: "src/faqs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Question", name: "title", widget: "string"}
      - {label: "Answer", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.html"}

  - name: "lexicon"
    label: "Lexicon Terms"
    folder: "src/lexicon"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Term", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Detailed Description", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Featured Term", name: "featured", widget: "boolean", default: false}
      - {label: "Popular Term", name: "popular", widget: "boolean", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/term.html"}

  - name: "blog"
    label: "Blog Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "postAuthor", widget: "string"}
      - {label: "Publish Date", name: "postDate", widget: "datetime"}
      - {label: "Summary", name: "postSummary", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Image Caption", name: "imageCaption", widget: "string", required: false}
      - {label: "Categories", name: "postCategories", widget: "list"}
      - {label: "Tags", name: "postTags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "resources"
    label: "Resources"
    folder: "src/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "item-title", widget: "string"}
      - {label: "Author", name: "item-author", widget: "string"}
      - {label: "Publication Date", name: "item-date", widget: "datetime"}
      - {label: "Resource Type", name: "item-type", widget: "string"}
      - {label: "URL", name: "item-url", widget: "string", required: false}
      - {label: "Summary", name: "item-summary", widget: "text"}
      - {label: "Categories", name: "item-categories", widget: "list"}
      - {label: "Tags", name: "item-tags", widget: "list"}